namespace :spectacle do
  configuration_file_path = Spectacle::Configuration::FILE_PATH

  desc "Install Spectacle"
  task :install do
    if File.exist?(configuration_file_path)
      puts "Spectacle is already installed."
      exit 0;
    end

    puts "Creating '#{configuration_file_path}' file."
    # Prompt the user for the globs that they want to use to determine which spec files to run
    # and write them to the configuration file.

    File.open(configuration_file_path, "w") do |f|
      f.write <<~YAML
        # This file was generated by the 'spectacle:install' Rake task.
        # You can modify this file to customize the behavior of Spectacle.
        defaults:
          all_specs_glob: "spec/**/*_spec.rb"
          no_specs_glob: "{}"

        # When no spec files are detected to run, Spectacle will run the specs defined in the 'on_empty_spec_set' key.
        on_empty_spec_set: "{{no_specs_glob}}"

        # If a file changes and it matches the glob, the corresponding pattern will be added to the list of spec files to run.
        # These will take precedence over the 'on_empty_spec_set' key.
        globs_matcher:
          "Gemfile": "{{all_specs_glob}}"
          "Gemfile.lock": "{{all_specs_glob}}"
          "config/**": "{{all_specs_glob}}"
      YAML
    end
  end

  desc "Collect spec dependencies"
  task :collect_dependencies do
    Spectacle::DependencyCollector.collect!
  end

  desc "Prints the list of specs that will be run to stdout"
  task :spec_determiner do
    puts "'#{Spectacle::SpecRunDeterminer.determine!}'"
  end

  desc "Download dependencies.json.gz"
  task :download_dependencies do
    Spectacle::DownloadDependenciesJson.download
  end
end
