require 'zlib'
require 'json'

require_relative "./helper_methods"

# We expect the SPEC_ARTIFACTS_DOWNLOAD_PATH to contain gzipped JSON files with the dependencies of each spec file.
# These files are generated by the DependencyTracer class.
# Each file looks like this:
# {
#   "spec/models/user_spec.rb": ["app/models/user.rb", "spec/factories/users.rb" ],
#   "spec/controllers/users_controller_spec.rb": ["app/controllers/users_controller.rb", "spec/factories/users.rb" ],
#   ...
# }
# This class reads all the files in the directory and combines them into a single hash, but inversed so that we map
# files to the spec files that depend on them.

# The output looks like this:
# {
#   "app/models/user.rb": ["spec/models/user_spec.rb"],
#   "spec/factories/users.rb": ["spec/models/user_spec.rb", "spec/controllers/users_controller_spec.rb"],
#   "app/controllers/users_controller.rb": ["spec/controllers/users_controller_spec.rb"],
#   ...
# }

# We write this output to a gzipped JSON file in the root of the OUTPUT_DIRECTORY called "dependencies.json.gz".

module Spectacle
  class DependencyCollector
    include Spectacle::HelperMethods

    def self.collect!
      new.collect!
    end

    def initialize
      @inverse_spec_dependencies = Hash.new { |h, k| h[k] = Set.new }
    end

    def collect!
      Dir.glob("#{SPEC_DEPENDENCY_OUTPUTS_DIRECTORY}/**/*.json.gz").each do |file|
        data = read_file(file)

        data.each do |spec_file, dependencies|
          dependencies.each do |dependency|
            @inverse_spec_dependencies[dependency].add(spec_file)
          end
        end
      end

      # Sort the dependencies for each file so that the output is deterministic
      @inverse_spec_dependencies.each { |k, v| @inverse_spec_dependencies[k] = v.sort.to_a }

      write_object_to_gzipped_json(@inverse_spec_dependencies, COLLECTED_DEPENDENCIES_FILE)

      nil
    end
  end
end
