# frozen_string_literal: true

require "rake/testtask"
require "spectracer"

load "spectracer/tasks/spectracer.rake"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test
